packages:
  - packages/*
  - plugins/*

catalogs:
  dep:
    commander: ^14.0.1
    consola: ^3.4.2
    rolldown: 1.0.0-beta.43

  dev:
    "@types/node": ^24.9.1
    rolldown-plugin-dts: ^0.16.11
    tsx: ^4.20.6
    typescript: ^5.9.3
    vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
