packages:
  - packages/*
  - plugins/*

catalogs:
  lib:
    rolldown: 1.0.0-beta.43

  dev:
    "@types/node": ^24.7.2
    current-changelog: ^1.2.0
    rolldown-plugin-dts: ^0.16.11
    typescript: ^5.9.3
    vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
